### ISSUE TITLE
Wrong command on front page 'atlas replay'

### ISSUE THREAD

**Issue by MaxwellDupre** [elcritch/figuro#50]
In **Trying it out** the command:

`atlas replay --cfgHere --ignoreUrls figuro/atlas.lock`

Does nothing because **replay** is not a command of atlas. I guess its been deprecated.
Looks like --**ignoreUrls** doesn't work either.
So running:

`atlas update --cfgHere  figuro/atlas.loc`

Produces:
[Info] (.) is the current workspace
Cloning into 'packages'...
remote: Enumerating objects: 8725, done.
remote: Counting objects: 100% (966/966), done.
remote: Compressing objects: 100% (56/56), done.
remote: Total 8725 (delta 923), reused 937 (delta 910), pack-reused 7759
Receiving objects: 100% (8725/8725), 3.60 MiB | 16.66 MiB/s, done.
Resolving deltas: 100% (5151/5151), done.
[Error] (figuro/atlas.lock) cannot resolve package name
[Info] (fig_ws) created: nim.cfg

Running

nim c -r figuro/tests/tclick.nim 

Produces:
Hint: used config file '/etc/nim/nim.cfg' [Conf]
Hint: used config file '/etc/nim/config.nims' [Conf]
Hint: used config file '/home/dougal/Documents/NIM/fig_ws/nim.cfg' [Conf]
Hint: used config file '/home/dougal/Documents/NIM/fig_ws/figuro/config.nims' [Conf]
Hint: used config file '/home/dougal/Documents/NIM/fig_ws/figuro/tests/config.nims' [Conf]
..................................................................................................................
.../fig_ws/figuro/figuro/shared.nim(4, 11) Error: cannot open file: pkg/variant

In the atlas.lock I see:
    "variant": {
      "dir": "$deps/variant",
      "url": "https://github.com/yglukhov/variant",
      "commit": "59caff018ed3b8b04c0e45ac260b4dc8fdef6ac3",
      "version": "0.3.0"

From Github the latest release of variant is 0.2.13 !

**Comment by elcritch** [comment]
Ah you’re probably on an older Atlas. The one that ships with Nim is pretty outdated.
