### ISSUE TITLE
[Button] How to set corner radius?

### ISSUE THREAD

**Issue by matkuki** [elcritch/figuro#58]
I'm testing with a modified `tclick` example, but cannot seems to change the corner/border radius of a `Button`.
I tried this, but it has no effect, the radius is always 10.0:
```nim
for i in 0 .. 4:
  buttonOf[int] "btn", captures=[i]:
    let btn = node
    with node:
      size 100'ux, 100'ux
      cornerRadius 0.0 # <- This has no effect!
      connect(doHover, self, btnHover)
      connect(doClick, node, btnClicked)
    if i == 0:
      connect(self, update, node, btnTick)
```

**Comment by elcritch** [comment]
Oh thanks for the bug. I'll look into it.

**Comment by elcritch** [comment]
Ah fixed it. It's a bit annoying, but to set widget styles as optional they need to use `withOptional self:` to avid overwriting the user's setting. I'm not 100% sure about this setup, but for now it works:

```nim
  withOptional self:
    cornerRadius 10.0'ui
```

But button was using: 

```nim
  with self:
    cornerRadius 10.0'ui
```
